# Generated by Django 5.2.2 on 2025-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='include_in_payroll',
            field=models.BooleanField(default=False, help_text='Expose this milestone in payroll calculations'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='include_in_reports',
            field=models.BooleanField(default=False, help_text='Flag this milestone for reporting dashboards'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='notify_on_reach',
            field=models.BooleanField(default=False, help_text='Send an email when a loan moves into this milestone'),
        ),
    ]
