# Generated by Django 5.2.2 on 2025-10-10 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeAssetNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_state', models.JSONField(blank=True, default=dict)),
                ('plain_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_asset_notes_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_asset_note', to='loan.loan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_asset_notes_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
