# Generated by Django 5.2.2 on 2026-01-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('view_all_loans', 'Can view all loans'), ('View_reports', 'Can view reports')]},
        ),
    ]
