# Generated by Django 5.2.2 on 2025-11-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('view_all_loans', 'Can view all loans'), ('view_report', 'Can view loan reports')]},
        ),
    ]
