# Generated by Django 5.2.2 on 2025-10-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_leave_balance_employee_yearly_paid_leaves'),
        ('loan', '0002_incomeassetnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lender',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='lenders',
        ),
        migrations.AddField(
            model_name='loan',
            name='lenders',
            field=models.ManyToManyField(blank=True, related_name='loans', to='employee.lender'),
        ),
    ]
