# Generated by Django 5.2.2 on 2025-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_broker_employee_lender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='milestone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
