# Generated by Django 5.2.2 on 2026-01-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanMilestoneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_history', to='loan.loan')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.milestone')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
