# Generated by Django 5.2.2 on 2025-12-16 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_milestone_include_in_payroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.milestone'),
        ),
    ]
