# Generated by Django 5.2.2 on 2025-09-30 10:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the milestone (e.g., Application, Underwriting)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this milestone', max_length=200, null=True)),
                ('color', models.CharField(default='#2563EB', help_text='Text color in hex format', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex code (e.g., #FF0000)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('background_color', models.CharField(default='#EEF2FF', help_text='Background color in hex format', max_length=7, validators=[django.core.validators.RegexValidator(message='Background color must be a valid hex code (e.g., #FF0000)', regex='^#[0-9A-Fa-f]{6}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', help_text='Current status of this milestone', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which milestones appear (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
