# Generated by Django 5.2.2 on 2025-12-16 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0005_attendancelog'),
        ('loan', '0003_alter_loan_milestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('view_all_loans', 'Can view all loans')]},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='support',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='team_manager',
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='lock_status',
            field=models.CharField(blank=True, choices=[('lock', 'Lock'), ('float', 'Float')], default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LoanRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(blank=True, to='employee.employee')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='loan.loan')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Loan Role Assignment',
                'verbose_name_plural': 'Loan Role Assignments',
                'unique_together': {('loan', 'role')},
            },
        ),
    ]
