# Generated by Django 5.2.2 on 2025-09-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
