# Generated by Django 5.2.2 on 2025-11-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_delete_lender_remove_loan_lenders_loan_lenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='notify_on_reach',
            field=models.BooleanField(default=False, help_text='Send an email when a loan moves into this milestone'),
        ),
    ]
