# Generated by Django 5.2.2 on 2025-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_milestone_notify_on_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='include_in_payroll',
            field=models.BooleanField(default=False, help_text='Expose this milestone in payroll calculations'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='include_in_reports',
            field=models.BooleanField(default=False, help_text='Flag this milestone for reporting dashboards'),
        ),
    ]
