# Generated by Django 5.2.2 on 2025-12-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loan_options_remove_loan_processor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'permissions': [('view_all_loans', 'Can view all loans'), ('View_reports', 'Can view reports')]},
        ),
    ]
