# Generated by Django 5.2.2 on 2025-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_checklistquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='submission_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
