# Generated by Django 5.2.2 on 2025-06-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loan_submission_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='submission_checklist',
        ),
        migrations.CreateModel(
            name='LoanChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='loan.loan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.checklistquestion')),
            ],
            options={
                'unique_together': {('loan', 'question')},
            },
        ),
    ]
