# Generated by Django 5.2.2 on 2025-11-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_milestone_include_in_payroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
