# Generated by Django 5.2.2 on 2025-11-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0006_employee_base_salary'),
        ('loan', '0006_loan_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ManyToManyField(blank=True, to='employee.employee')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='loan.loan')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
