# Generated by Django 5.2.2 on 2025-06-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_loancontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_reimbursed', models.CharField(blank=True, max_length=255)),
                ('ctc_date', models.CharField(blank=True, max_length=255)),
                ('escrow_contact_name', models.CharField(blank=True, max_length=255)),
                ('escrow_phone', models.CharField(blank=True, max_length=255)),
                ('lender_credit', models.CharField(blank=True, max_length=255)),
                ('loan_officer', models.CharField(blank=True, max_length=255)),
                ('property_address', models.CharField(blank=True, max_length=255)),
                ('rate_lock_expiration', models.CharField(blank=True, max_length=255)),
                ('subordination', models.CharField(blank=True, max_length=255)),
                ('investor', models.CharField(blank=True, max_length=255)),
                ('borrower_file_number', models.CharField(blank=True, max_length=255)),
                ('citi_login_and_password', models.CharField(blank=True, max_length=255)),
                ('escrow_email', models.CharField(blank=True, max_length=255)),
                ('impounds', models.CharField(blank=True, max_length=255)),
                ('lender_fees', models.CharField(blank=True, max_length=255)),
                ('loan_amount', models.CharField(blank=True, max_length=255)),
                ('loan_program', models.CharField(blank=True, max_length=255)),
                ('purchase_or_refinance', models.CharField(blank=True, max_length=255)),
                ('rate', models.CharField(blank=True, max_length=255)),
                ('melp_m_or_bpm', models.CharField(blank=True, max_length=255)),
                ('second_lender', models.CharField(blank=True, max_length=255)),
                ('doc_request_date', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(blank=True, max_length=255)),
                ('cd_signed_date', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_orders', to='loan.loan')),
            ],
        ),
    ]
