# Generated by Django 5.2.2 on 2025-11-09 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('loan', '0007_loanroleassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanroleassignment',
            options={'verbose_name': 'Loan Role Assignment', 'verbose_name_plural': 'Loan Role Assignments'},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='support',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='team_leader',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='team_manager',
        ),
        migrations.AddField(
            model_name='loanroleassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='loanroleassignment',
            unique_together={('loan', 'role')},
        ),
    ]
