# Generated by Django 5.2.2 on 2025-06-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_docorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDocStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('appraisal', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('voe', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('hoi', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('survey', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('credit_card', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('fha_case', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('flood_cert', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('condo_docs', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('pay_off', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('final_inspection', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('subordination', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('received', 'Received'), ('n/a', 'N/A')], default='n/a', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doc_status', to='loan.loan')),
            ],
        ),
    ]
