# Generated by Django 5.2.2 on 2025-11-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_alter_loan_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='milestone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
