# Generated by Django 5.2.2 on 2025-07-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='external_id',
            field=models.CharField(blank=True, help_text='MISMO LoanIdentifier (for XML‐imported loans)', max_length=40, null=True, unique=True, verbose_name='Import ID'),
        ),
        migrations.AddField(
            model_name='loan',
            name='import_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('xml', 'XML')], default='manual', help_text='Whether record was created by user or XML', max_length=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='imported_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this loan was last imported', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='raw_xml',
            field=models.TextField(blank=True, help_text='Stored XML payload (for auditing or re‐parsing)', null=True),
        ),
    ]
