# Generated by Django 5.2.2 on 2025-11-09 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_alter_loan_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.milestone'),
        ),
    ]
