# Generated by Django 5.2.2 on 2025-07-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('loan', '0015_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.broker'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_officer', to='employee.loanofficer'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_support', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_team_leader', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='team_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_team_manager', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='processor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_processor', to='employee.employee'),
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
