# Generated by Django 5.2.2 on 2025-08-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0016_alter_loan_broker_alter_loan_loan_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='loan.loan'),
        ),
    ]
