# Generated by Django 5.2.2 on 2025-08-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_permission_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
