# Generated by Django 4.2.30 on 2026-05-11 05:53

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('loan', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the payroll month')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Monthly base salary', max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('working_days', models.IntegerField(default=26)),
                ('present_days', models.IntegerField(default=0)),
                ('paid_leave_days', models.IntegerField(default=0)),
                ('unpaid_leave_days', models.IntegerField(default=0)),
                ('payable_days', models.IntegerField(default=0)),
                ('prorated_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('loan_count', models.IntegerField(default=0)),
                ('incentive_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('incentive_breakdown', models.JSONField(blank=True, default=dict, help_text='Detail of incentive calculations')),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Total before deductions', max_digits=12)),
                ('pf_employee_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pf_employer_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('eps_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('esi_employee_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('esi_employer_contribution', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Loans, advances, etc.', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employee.employee')),
            ],
            options={
                'ordering': ['-month', 'employee__name'],
                'permissions': [('approve_payroll', 'Can approve payroll'), ('view_all_payrolls', 'Can view all employee payrolls')],
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_employee_percent', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Employee PF contribution %', max_digits=5)),
                ('pf_employer_percent', models.DecimalField(decimal_places=2, default=Decimal('3.67'), help_text='Employer PF contribution %', max_digits=5)),
                ('eps_percent', models.DecimalField(decimal_places=2, default=Decimal('8.33'), help_text='EPS contribution %', max_digits=5)),
                ('esi_employee_percent', models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='Employee ESI contribution %', max_digits=5)),
                ('esi_employer_percent', models.DecimalField(decimal_places=2, default=Decimal('3.25'), help_text='Employer ESI contribution %', max_digits=5)),
                ('standard_working_days', models.IntegerField(default=26, help_text='Standard working days per month for proration')),
                ('hra_percent', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='HRA as % of basic salary', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Settings',
            },
        ),
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=50)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payroll.employeepayroll')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IncentiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_files', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_files', models.IntegerField(blank=True, help_text="Null means 'and above'", null=True)),
                ('amount_per_file', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules apply first (for overlapping ranges)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(blank=True, help_text='Specific milestone to count, or null for all payroll-eligible', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_rules', to='loan.milestone')),
                ('roles', models.ManyToManyField(blank=True, related_name='incentive_rules', to='auth.group')),
            ],
            options={
                'ordering': ['-priority', 'min_files'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='payroll_inc_is_acti_309c83_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='employeepayroll',
            index=models.Index(fields=['month', 'status'], name='payroll_emp_month_5eed01_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepayroll',
            index=models.Index(fields=['employee', 'month'], name='payroll_emp_employe_fca57f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeepayroll',
            unique_together={('employee', 'month')},
        ),
    ]
