# Generated by Django 5.2.2 on 2025-10-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_employee_leave_balance_employee_yearly_paid_leaves'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_employee_percent', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('pf_employer_percent', models.DecimalField(decimal_places=2, default=3.67, max_digits=5)),
                ('eps_percent', models.DecimalField(decimal_places=2, default=8.33, max_digits=5)),
                ('esi_employee_percent', models.DecimalField(decimal_places=2, default=0.75, max_digits=5)),
                ('esi_employer_percent', models.DecimalField(decimal_places=2, default=3.25, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_employee_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_employer_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eps_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esi_employee_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esi_employer_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentive_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='IncentiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=100)),
                ('min_files', models.IntegerField()),
                ('max_files', models.IntegerField(blank=True, null=True)),
                ('amount_per_file', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.role')),
            ],
        ),
    ]
