# Generated by Django 5.2.2 on 2025-10-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentiverule',
            name='role',
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='role',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
