# Generated by Django 5.2.2 on 2025-10-30 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_delete_lender_remove_loan_lenders_loan_lenders'),
        ('payroll', '0002_remove_incentiverule_role_incentiverule_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentiverule',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_rules', to='loan.milestone'),
        ),
    ]
