# Generated by Django 5.2.2 on 2025-11-08 17:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0006_employee_base_salary'),
        ('loan', '0005_milestone_include_in_payroll_and_more'),
        ('payroll', '0003_alter_incentiverule_milestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=50)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='employeepayroll',
            options={'ordering': ['-month', 'employee__name'], 'permissions': [('approve_payroll', 'Can approve payroll'), ('view_all_payrolls', 'Can view all employee payrolls')]},
        ),
        migrations.AlterModelOptions(
            name='incentiverule',
            options={'ordering': ['-priority', 'min_files']},
        ),
        migrations.AlterModelOptions(
            name='payrollsettings',
            options={'verbose_name': 'Payroll Settings'},
        ),
        migrations.AlterUniqueTogether(
            name='employeepayroll',
            unique_together={('employee', 'month')},
        ),
        migrations.RemoveField(
            model_name='incentiverule',
            name='role',
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly base salary', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='incentive_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Detail of incentive calculations'),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='loan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Loans, advances, etc.', max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='paid_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='payable_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='prorated_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='unpaid_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='working_days',
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='name',
            field=models.CharField(default='Default Rule', help_text="Rule description (e.g., 'Team Leader Pre-Qualified Tier 1')", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority rules apply first (for overlapping ranges)'),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='incentive_rules', to='auth.group'),
        ),
        migrations.AddField(
            model_name='incentiverule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='hra_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='HRA as % of basic salary', max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='standard_working_days',
            field=models.IntegerField(default=26, help_text='Standard working days per month for proration'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='eps_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='esi_employee_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='esi_employer_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, help_text='Total before deductions', max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='incentive_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='month',
            field=models.DateField(help_text='First day of the payroll month'),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='pf_employee_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='pf_employer_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='amount_per_file',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='max_files',
            field=models.IntegerField(blank=True, help_text="Null means 'and above'", null=True),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='Specific milestone to count, or null for all payroll-eligible', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_rules', to='loan.milestone'),
        ),
        migrations.AlterField(
            model_name='incentiverule',
            name='min_files',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='eps_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.33'), help_text='EPS contribution %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='esi_employee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='Employee ESI contribution %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='esi_employer_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.25'), help_text='Employer ESI contribution %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='pf_employee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Employee PF contribution %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='pf_employer_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.67'), help_text='Employer PF contribution %', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='employeepayroll',
            index=models.Index(fields=['month', 'status'], name='payroll_emp_month_5eed01_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepayroll',
            index=models.Index(fields=['employee', 'month'], name='payroll_emp_employe_fca57f_idx'),
        ),
        migrations.AddIndex(
            model_name='incentiverule',
            index=models.Index(fields=['is_active', 'priority'], name='payroll_inc_is_acti_309c83_idx'),
        ),
        migrations.AddField(
            model_name='payrollauditlog',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payroll.employeepayroll'),
        ),
        migrations.AddField(
            model_name='payrollauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='employeepayroll',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employeepayroll',
            name='total_deduction',
        ),
    ]
