# Generated by Django 5.2.2 on 2025-11-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payrollauditlog_alter_employeepayroll_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentiverule',
            name='name',
        ),
    ]
