# Generated by Django 5.2.2 on 2025-11-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_remove_incentiverule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentiverule',
            name='name',
            field=models.CharField(default=1, help_text="Rule description (e.g., 'Team Leader Pre-Qualified Tier 1')", max_length=200),
            preserve_default=False,
        ),
    ]
