# Generated by Django 5.2.2 on 2025-11-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_incentiverule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentiverule',
            name='name',
        ),
    ]
