# Generated by Django 5.2.2 on 2025-07-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('NMLS', models.CharField(db_index=True, max_length=50, unique=True)),
                ('primary_phone', models.CharField(db_index=True, max_length=25, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=25, unique=True)),
                ('address', models.TextField()),
                ('company_address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='broker_logos/')),
                ('designation', models.CharField(db_index=True, max_length=100)),
                ('entregar_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('entregar_fax', models.CharField(blank=True, max_length=25, null=True)),
                ('entregar_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='broker_signatures/')),
                ('doc_order_option', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_checklist', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('company_email', models.EmailField(db_index=True, default='default@example.com', max_length=254, unique=True)),
                ('contact_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('position', models.CharField(choices=[('junior_processor', 'Junior Processor'), ('processor', 'Processor'), ('team_lead', 'Team Lead'), ('team_manager', 'Team Manager')], db_index=True, default='junior_processor', max_length=20)),
                ('performance_score', models.FloatField(db_index=True, default=0.0)),
                ('experience_months', models.PositiveIntegerField(db_index=True, default=0)),
                ('bank_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('account_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('bank_details', models.TextField(blank=True, db_index=True)),
                ('address', models.TextField(blank=True, db_index=True)),
                ('date_of_join', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], db_index=True, default='active', max_length=20)),
                ('login_password', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('leave_balance', models.FloatField(db_index=True, default=0.0)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('contact_number', models.CharField(db_index=True, max_length=25, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('NMLS', models.CharField(db_index=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('broker_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_officers', to='employee.broker')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('employees', models.ManyToManyField(related_name='meetings', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
