# Generated by Django 5.2.2 on 2026-01-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('-date',), 'permissions': [('view_latelogins', 'Can view Login records')]},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='base_salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
