# Generated by Django 5.2.6 on 2025-09-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicholiday',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True if imported from official public holiday calendar'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='source',
            field=models.CharField(blank=True, help_text="e.g. 'python-holidays:US-IL' or 'manual'", max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['date'], name='employee_pu_date_afb39d_idx'),
        ),
    ]
