# Generated by Django 5.2.2 on 2025-08-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employee', '0002_remove_employee_position_employee_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
