# Generated by Django 5.2.2 on 2025-11-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_attendancelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('-date',), 'permissions': [('view_latelogins', 'Can view late login records')]},
        ),
    ]
