# Generated by Django 5.2.6 on 2025-09-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_publicholiday_options_publicholiday_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
