# Generated by Django 5.2.2 on 2026-01-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_attendance_options_remove_employee_base_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='basic',
            new_name='base_salary',
        ),
    ]
