# Generated by Django 5.2.2 on 2025-11-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_attendance_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
    ]
