# Generated by Django 5.2.2 on 2026-01-17 18:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_basic_employee_base_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly gross salary before incentives and deductions.', max_digits=12),
        ),
    ]
