# Generated by Django 5.2.6 on 2025-09-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_meeting_date_remove_meeting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequests',
            name='approval_type',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=20, null=True),
        ),
    ]
