# Generated by Django 5.2.6 on 2025-10-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_leaverequests_approval_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_balance',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='yearly_paid_leaves',
            field=models.IntegerField(default=12),
        ),
    ]
