# Generated by Django 5.2.2 on 2026-01-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_bonus_amount_employee_comp_off_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
