# Generated by Django 5.2.2 on 2025-12-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('EARLY', 'Early'), ('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave (Paid)'), ('UNPAID_LEAVE', 'Unpaid Leave')], max_length=20, null=True),
        ),
    ]
