# Generated by Django 5.2.7 on 2025-10-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_leave_balance_employee_yearly_paid_leaves'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'permissions': [('dropview_broker', 'Can view dropdown'), ('sidebar_broker', 'Can view in sidebar')]},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('dropview_employee', 'Can view dropdown'), ('sidebar_employee', 'Can view in sidebar')]},
        ),
        migrations.AlterModelOptions(
            name='lender',
            options={'permissions': [('dropview_lender', 'Can view dropdown'), ('sidebar_lender', 'Can view in sidebar')]},
        ),
        migrations.AlterModelOptions(
            name='loanofficer',
            options={'permissions': [('dropview_loanofficer', 'Can view dropdown'), ('sidebar_loanofficer', 'Can view in sidebar')]},
        ),
    ]
