# Generated by Django 5.2.7 on 2025-10-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_broker_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'permissions': [('sidebar_broker', 'Can view in sidebar')]},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('sidebar_employee', 'Can view in sidebar')]},
        ),
        migrations.AlterModelOptions(
            name='lender',
            options={'permissions': [('sidebar_lender', 'Can view in sidebar')]},
        ),
        migrations.AlterModelOptions(
            name='loanofficer',
            options={'permissions': [('sidebar_loanofficer', 'Can view in sidebar')]},
        ),
    ]
