# Generated by Django 5.2.2 on 2026-01-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_date_of_joining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_joining',
        ),
    ]
