# Generated by Django 5.2.2 on 2025-12-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_attendance_leave_type_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='leave_type',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('EARLY', 'Early'), ('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave (Paid)'), ('UNPAID_LEAVE', 'Unpaid Leave')], max_length=20),
        ),
    ]
