# Generated by Django 5.2.2 on 2025-12-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_attendance_leave_type_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
