# Generated by Django 5.2.7 on 2025-10-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_broker_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
