# Generated by Django 5.2.2 on 2025-12-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_bank_account_no_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='arrear_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='conveyance_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='food_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='House Rent Allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_reimbursement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='uniform_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
