# Generated by Django 5.2.2 on 2026-01-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_arrear_salary_employee_basic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='phone',
            field=models.CharField(db_index=True, max_length=25),
        ),
    ]
