# Generated by Django 5.2.2 on 2025-09-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_attendance_created_at_attendance_logout_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
