# Generated by Django 5.2.2 on 2026-01-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_broker_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True),
        ),
    ]
