# Generated by Django 5.2.2 on 2025-09-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_attendance_unique_together'),
    ]

    operations = [
        
       
    ]
