# Generated by Django 5.2.2 on 2025-09-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_attendance_login_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
