# Generated by Django 5.2.2 on 2025-09-10 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('counted_from', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EARLY', 'Early'), ('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave')], max_length=20)),
                ('minutes_late', models.IntegerField(blank=True, null=True)),
                ('worked_minutes', models.IntegerField(blank=True, null=True)),
                ('total_break_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employee.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.shift')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('break_out', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='employee.attendance')),
            ],
        ),
    ]
