# Generated by Django 5.2.2 on 2025-09-13 10:20

import employee.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_monthlyattendancesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='break_in',
            field=models.DateTimeField(default=employee.utils.now_cst),
        ),
    ]
