# Generated by Django 5.2.2 on 2025-09-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_break_break_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequests',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
