# Generated by Django 5.2.2 on 2025-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_leaverequests_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('EARLY', 'Early'), ('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave (Paid)'), ('UNPAID_LEAVE', 'Unpaid Leave')], max_length=20),
        ),
    ]
