# Generated by Django 5.2.2 on 2025-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='unpaid_leave_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
