# Generated by Django 5.2.2 on 2025-09-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_monthlyattendancesummary_unpaid_leave_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequests',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
