# Generated by Django 5.2.2 on 2025-09-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_alter_leaverequests_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequests',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
