# Generated by Django 5.2.2 on 2025-09-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_leaverequests_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequests',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='start_date',
            field=models.DateField(),
        ),
    ]
