# Generated by Django 5.2.2 on 2025-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_remove_leaverequests_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=255)),
                ('account_executive_name', models.CharField(blank=True, max_length=255, null=True)),
                ('executive_email', models.EmailField(max_length=254, unique=True)),
                ('executive_phone', models.CharField(max_length=20, unique=True)),
                ('executive_address', models.TextField(blank=True, null=True)),
                ('account_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_email', models.EmailField(max_length=254, unique=True)),
                ('manager_contact', models.CharField(max_length=20, unique=True)),
                ('manager_address', models.TextField(blank=True, null=True)),
                ('mortgage_clause', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
