# Generated by Django 5.2.2 on 2025-09-19 06:43

import employee.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_lender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequests',
            name='created_at',
            field=models.DateTimeField(default=employee.utils.now_cst, editable=False),
        ),
    ]
