# Generated by Django 5.2.2 on 2025-09-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_alter_leaverequests_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_of', to='employee.employee')),
                ('members', models.ManyToManyField(related_name='member_of_teams', to='employee.employee')),
            ],
        ),
    ]
