# Generated by Django 5.2.2 on 2025-09-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_teamlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
