# Generated by Django 5.2.2 on 2025-09-19 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_teamlead_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_team', to='employee.employee', verbose_name='Team Manager')),
                ('team_leads', models.ManyToManyField(blank=True, related_name='managers', to='employee.teamlead', verbose_name='Team Leads')),
            ],
            options={
                'verbose_name': 'Team Manager',
                'verbose_name_plural': 'Team Managers',
            },
        ),
    ]
