# Generated by Django 5.2.2 on 2025-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_alter_team_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='total_overtime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyattendancesummary',
            name='total_worked_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
