# Generated by Django 5.2.2 on 2025-09-21 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_monthlyattendancesummary_total_overtime_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['employee', 'status'], name='employee_co_employe_068756_idx'),
        ),
    ]
