# Generated by Django 5.2.2 on 2025-09-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_complaint_responder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
