# Generated by Django 5.2.2 on 2025-09-22 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='EmployeeToken',
        ),
    ]
