# Generated by Django 5.2.2 on 2025-09-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_rename_token_employeetoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetoken',
            options={'ordering': ['-created_at'], 'permissions': [('view_tokens', 'Can view tokens'), ('approve_tokens', 'Can approve tokens')]},
        ),
    ]
