# Generated by Django 5.2.2 on 2025-09-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_employeebreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebreak',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
