# Generated by Django 5.2.2 on 2025-07-03 04:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=120)),
                ('row_pk', models.CharField(max_length=120)),
                ('operation', models.CharField(max_length=8)),
                ('diff', models.JSONField()),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('request_id', models.UUIDField(db_index=True)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['table_name', 'row_pk'], name='audit_audit_table_n_a1cff7_idx'), models.Index(fields=['changed_at'], name='audit_audit_changed_729482_idx')],
            },
        ),
    ]
