# Generated by Django 4.2.30 on 2026-05-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='employee.employee'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['table_name', 'row_pk'], name='audit_audit_table_n_a1cff7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['changed_at'], name='audit_audit_changed_729482_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor'], name='audit_audit_actor_i_40b234_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['employee'], name='audit_audit_employe_0b19c9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id'], name='audit_audit_request_c59dc1_idx'),
        ),
    ]
