# Generated by Django 5.2.2 on 2025-08-20 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditevent_employee_alter_auditevent_actor'),
        ('employee', '0003_alter_employee_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='request_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='row_pk',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor'], name='audit_audit_actor_i_40b234_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['employee'], name='audit_audit_employe_0b19c9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id'], name='audit_audit_request_c59dc1_idx'),
        ),
    ]
